FIGURE_CONTENT = {
    "F01": {
        "title": "Paired library-size quality control",
        "caption": "Gene-level count totals for each included sample, connected within patient and shown against the predefined one-million-count QC minimum.",
        "shows": "All 42 included samples are above the minimum. Several matched tissues differ substantially in count depth, which is why model-based normalization remains necessary.",
        "does_not_prove": "Library size alone cannot prove sample integrity, remove batch effects, or establish biological comparability.",
        "source": "results_v2/metadata/paired_manifest.tsv; results/qc/qc_summary.tsv",
        "script": "scripts/04-figures/01_publication_figures_paired_v2.R",
    },
    "F02": {
        "title": "Paired-sample PCA",
        "caption": "Principal-component analysis of the 2,000 most variable genes after DESeq2 variance-stabilizing transformation, with matched tissues connected.",
        "shows": "The first two components summarize major expression variation and show broad condition-associated structure with patient-level heterogeneity.",
        "does_not_prove": "PCA is exploratory, not a hypothesis test. Separation may reflect condition, cell mixture, batch, or unmeasured covariates.",
        "source": "results_v2/deseq2/deseq2_paired_v2_vst.tsv",
        "script": "scripts/04-figures/02_pca_paired_v2.R",
    },
    "F03": {
        "title": "MA plot of paired differential expression",
        "caption": "Shrunken Tumor-versus-Normal log2 fold change against mean normalized abundance. Grey distinguishes FDR-only genes from genes also passing the absolute effect-size threshold.",
        "shows": "Statistically supported differences occur in both directions over a range of expression levels.",
        "does_not_prove": "A statistically supported expression difference is not evidence of causation, clinical value, or biomarker validity.",
        "source": "results_v2/deseq2/deseq2_paired_v2_results.tsv",
        "script": "scripts/04-figures/03_ma_paired_v2.R",
    },
    "F04": {
        "title": "Volcano plot of effect and evidence",
        "caption": "Shrunken log2 fold change versus adjusted statistical evidence. Labels are selected symmetrically from both directions without prior biological preference.",
        "shows": "The strict reporting rule identifies more Normal-higher than Tumor-higher genes in this cohort.",
        "does_not_prove": "Genes at the visual extremes are candidates for interpretation, not validated drivers or diagnostic markers.",
        "source": "results_v2/deseq2/deseq2_paired_v2_results.tsv",
        "script": "scripts/04-figures/04_volcano_paired_v2.R",
    },
    "F05": {
        "title": "Balanced top-gene heatmap",
        "caption": "Up to 20 Tumor-higher and 20 Normal-higher genes passing the primary reporting rule, shown as row-wise z-scores from the VST matrix.",
        "shows": "Selected genes display recurring condition-associated patterns, with substantial patient-level variation.",
        "does_not_prove": "Row clustering is descriptive and does not define breast-cancer subtypes or patient-level classifiers.",
        "source": "DE result table, VST matrix, and paired sample manifest",
        "script": "scripts/04-figures/05_heatmap_paired_v2.R",
    },
    "F06": {
        "title": "Hallmark gene-set enrichment",
        "caption": "Balanced significant Hallmark pathways. Positive NES is enrichment toward Tumor-higher genes; negative NES is enrichment toward Normal-higher genes.",
        "shows": "E2F, MYC, G2M-checkpoint and mTORC1 programs are enriched toward the Tumor-higher side. Negative NES pathways are enriched toward the Normal-higher side.",
        "does_not_prove": "GSEA identifies coordinated rank patterns; it does not show pathway activation mechanism or clinical actionability.",
        "source": "results_v2/enrichment/hallmark_gsea_paired_v2.tsv",
        "script": "scripts/04-figures/06_hallmark_bar_paired_v2.R",
    },
    "F07": {
        "title": "Directional GO Biological Processes",
        "caption": "Separate Tumor-higher and Normal-higher ORAs use the same background. The plot shows ten significant representatives per direction after Wang reduction and a documented two-per-keyword-family display cap.",
        "shows": "Tumor-higher genes emphasize division/chromosome themes; Normal-higher genes include circulation, muscle, extracellular-matrix and metabolic/tissue-context themes.",
        "does_not_prove": "GO terms are overlapping annotations. Enrichment does not demonstrate a causal mechanism or independent validation.",
        "source": "directional full and representative GO BP ORA tables",
        "script": "scripts/04-figures/07_go_bp_dotplot_paired_v2.R",
    },
}

PIPELINE_STAGES = [
    ("1. GEO metadata", "Parse accession, titles, tissue labels, genotype and batch fields.", "data/metadata/metadata.tsv", "Incorrect labels or patient IDs."),
    ("2. HTSeq counts", "Remove HTSeq technical rows and outer-join 74 sample files by gene ID.", "data/processed/counts.tsv", "Missing, duplicate, non-integer or negative counts."),
    ("3. QC and cohort", "Calculate count totals, apply the 1e6 minimum, and require one passing Tumor and Normal per patient.", "results_v2/metadata/paired_manifest.tsv", "Low depth, unmatched patients or duplicate tissues."),
    ("4. Paired DESeq2", "Fit ~ patient_id + condition_main to raw counts and test Tumor versus Normal.", "results_v2/deseq2/deseq2_paired_v2_results.tsv", "Wrong reference, sample order, outliers or invalid counts."),
    ("5. Hallmark GSEA", "Rank mapped gene symbols by the DESeq2 Wald statistic and run fgseaMultilevel.", "results_v2/enrichment/hallmark_gsea_paired_v2.tsv", "Identifier loss, duplicate symbols or unstable ranking."),
    ("6. GO BP ORA", "Run combined supplementary, Tumor-higher and Normal-higher tests against one tested-gene universe; reduce redundancy only for presentation.", "results_v2/enrichment/go_bp_ora_*_paired_v2.tsv", "Wrong direction, background, annotation loss or redundant terms."),
    ("7. Figures and validation", "Render F01-F07, create PDFs, checksums and strict output manifests.", "figures_v2/final; results_v2/output_manifest.tsv", "Missing, empty or non-canonical artifacts."),
]

METHODS = {
    "RNA-seq count data": "Each matrix cell is the number of reads/fragments assigned to a gene in one sample. Counts are discrete and their variability increases with their mean.",
    "Sequencing depth": "Samples can have different total assigned counts. A deeper sample can show larger raw counts even when biology is unchanged.",
    "Normalization": "DESeq2 estimates one size factor per sample so the model compares relative abundance rather than raw depth.",
    "Negative-binomial model": "DESeq2 models counts with a distribution that allows variance to exceed the mean, a common property of biological count data.",
    "Paired design": "The patient term absorbs stable between-person differences. The condition term then estimates the Tumor-versus-Normal difference within matched patients.",
    "Wald test": "The estimated condition effect is divided by its standard error. A large absolute statistic is less compatible with a zero-effect null model.",
    "Log2 fold change": "A value of +1 means approximately twice as high in Tumor; -1 means approximately twice as high in Normal.",
    "P-value": "Under the model and a zero-effect null hypothesis, it measures how unusual an effect at least this extreme would be. It is not the probability that the null is true.",
    "Benjamini-Hochberg FDR": "Genes are tested together. BH adjusted p-values control the expected false-discovery proportion among discoveries under its assumptions.",
    "Shrinkage": "Noisy log2 fold changes are pulled toward zero, especially when information is weak. This stabilizes ranking and visualization.",
    "PCA": "PCA compresses many gene measurements into orthogonal directions that capture the largest variance. It is exploratory.",
    "Z-score": "For each heatmap gene, subtract its sample mean and divide by its sample standard deviation. Color then shows relative, not absolute, expression.",
    "GSEA": "GSEA asks whether members of a predefined gene set accumulate near one end of a ranked gene list.",
    "NES": "The normalized enrichment score adjusts the raw GSEA score for gene-set size. Its sign follows the ranked contrast direction.",
    "GO ORA": "Over-representation analysis asks whether selected DE genes occur in a GO term more often than expected relative to the tested background. Direction must come from separate Tumor-higher and Normal-higher input lists.",
}

VIVA_QA = [
    ("What is the purpose of OncoRNA?", "This project explores gene-expression differences between breast Tumor and matched Normal tissue in GSE306117. It is a learning and portfolio analysis, not a clinical test."),
    ("What data did you use?", "I used public gene-level HTSeq count files and sample metadata from GEO accession GSE306117. The analysis includes 21 patients with one Tumor and one matched Normal sample each."),
    ("Why are matched samples valuable?", "Each patient provides their own Normal baseline. This helps separate the common Tumor-Normal difference from stable differences between patients, although it does not remove every confounder."),
    ("What is RNA-seq in this project?", "RNA-seq provides counts representing how many sequencing fragments were assigned to each gene in each sample. These counts are used as indirect measurements of RNA abundance."),
    ("How is the count matrix organised?", "Rows are genes and columns are samples. Each cell contains a non-negative integer count for one gene in one sample."),
    ("Why did you use DESeq2?", "DESeq2 is designed for overdispersed RNA-seq count data. It estimates normalization and dispersion and can fit the paired design used here."),
    ("Why use a negative-binomial distribution?", "RNA-seq counts often vary more than a Poisson model would allow. The negative-binomial model includes a dispersion term for this extra biological and technical variability."),
    ("How does normalization work here?", "DESeq2 estimates a size factor for each sample. This accounts for relative count-depth differences before comparing expression, rather than dividing every gene by the same fixed total."),
    ("What does the model formula mean?", "The model is `~ patient_id + condition_main`. The patient term controls each person's baseline, while the condition term estimates the remaining Tumor-versus-Normal difference."),
    ("What is the reference and contrast?", "Normal is the reference level and the contrast is Tumor versus Normal. Positive log2 fold changes are therefore Tumor-higher, while negative values are Normal-higher."),
    ("What does the Wald test do?", "The Wald test compares the estimated condition coefficient with its standard error. A large absolute statistic is less compatible with a zero condition effect under the fitted model."),
    ("What is log2 fold change?", "It describes effect direction and magnitude on a base-two scale. A value near +1 means about two-fold higher in Tumor, while -1 means about two-fold higher in Normal."),
    ("What does a p-value mean?", "It measures how unusual the observed evidence would be under a zero-effect null model. It is not the probability that a gene is truly differential."),
    ("Why use Benjamini-Hochberg FDR?", "The analysis tests thousands of genes, so some small p-values occur by chance. BH adjustment limits the expected false-discovery proportion among reported findings under its assumptions."),
    ("What is independent filtering?", "DESeq2 removes very low-information genes from multiple-testing adjustment using a rule independent of the condition test under the null. This can improve power without changing the raw count model."),
    ("Why shrink log2 fold changes?", "Weakly supported fold-change estimates can be unstable, especially for low-count genes. Shrinkage pulls uncertain estimates toward zero so effect ranking and plots are more stable."),
    ("What does PCA show?", "PCA summarizes the largest expression-variation patterns after VST. It can reveal broad structure and unusual samples, but it is exploratory and is not a significance test."),
    ("How do you read the MA plot?", "The x-axis shows mean abundance and the y-axis shows shrunken Tumor-Normal effect. It helps check whether effect estimates change with expression strength."),
    ("How do you read the volcano plot?", "The x-axis shows effect direction and magnitude, while the y-axis shows adjusted statistical evidence. Labelled genes are examples for interpretation, not validated biomarkers."),
    ("What does the heatmap show?", "It shows relative VST expression for 20 Tumor-higher and 20 Normal-higher genes across matched samples. Row z-scores compare samples within each gene and do not define molecular subtypes."),
    ("What is Hallmark GSEA?", "GSEA tests whether genes from a predefined Hallmark set collect toward one end of the full ranked list. Positive NES points toward Tumor-higher genes and negative NES toward Normal-higher genes."),
    ("How is GO ORA different from GSEA?", "ORA starts with a selected gene list, whereas GSEA uses the full ranking. The main GO presentation uses separate Tumor-higher and Normal-higher lists so direction is not lost."),
    ("What are the main findings?", "There are 6,315 genes at padj below 0.05 and 1,636 that also pass the effect-size rule. Cell-cycle programs are enriched toward the Tumor-higher ranking, while directional GO results also show distinct Normal-higher tissue-context themes."),
    ("What are the main limitations?", "This is one bulk-tissue cohort with mixed cell populations and incomplete annotation mapping. There is no independent cohort, protein assay, functional experiment or clinical validation."),
    ("What should be validated next?", "The paired model should be repeated in an independent cohort with closer attention to technical and cell-composition effects. Selected genes or pathways would then need orthogonal experimental validation."),
]

CAN_SUPPORT = [
    "A reproducible paired differential-expression analysis of this public GSE306117 cohort.",
    "Statistical association between tissue condition and gene expression after controlling patient baseline.",
    "Pathway-level hypotheses supported by ranked enrichment and over-representation analyses.",
    "A transparent foundation for external replication and experimental validation.",
]

CANNOT_SUPPORT = [
    "Causation or a molecular mechanism.",
    "Clinical diagnosis, prognosis or treatment recommendation.",
    "Validated biomarkers or patient-level prediction.",
    "Population-wide generalization from one cohort.",
    "Laboratory confirmation or independent-cohort replication.",
]
